# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.define "director" do |node|
    node.vm.network "public_network", :dev => "br0", :mac => "52:54:00:64:61:06"
    node.vm.provider "libvirt" do |hardware|
      node.vm.hostname = "director.localdomain"
      hardware.memory = "4096"
      hardware.cpus = "2"
    end
  end
end
